### ISSUE TITLE
Issue with field Iteration Path and value @Current Iteration

### ISSUE THREAD

**Issue by jmsvl** [figueiredorui/1-click-child-links#1]
Hello Rui,

Thanks a lot for this great extension.

I'm having an issue when the template has the filed Iteration Path (and the value @CurrentIteration) as the Child Task is not created. Can you help?

![image](https://cloud.githubusercontent.com/assets/6940508/21181482/0f949076-c1f6-11e6-91af-6e2945572388.png)

**Comment by figueiredorui** [comment]
Hi Jorge,
Thanks for your feedback.
I've fixed the issue and now the extension supports @CurrentIteration.

**Comment by dwhittenburg** [comment]
I was able to add a template to a Task work item type and see this work, but it isn't working for Bug and PBI work item types.  Anything I should try?

![image](https://cloud.githubusercontent.com/assets/7723714/21427216/23719a9a-c821-11e6-8e1f-e7bef41a90cd.png)
