### ISSUE TITLE
How does this differ from 1-Click-Tasks, and is there a way to add WITs to a 1-click action?

### ISSUE THREAD

**Issue by mcascone** [figueiredorui/1-click-child-links#10]
Hi,
I've been using 1-Click-Tasks, and just saw this new version 1-Click-Child-Links. I can't really tell how it's different from 1-Click-Tasks?
I was hoping it would let you set a default set of child links - like Test Cases - that you could create with the 1-Click action.
Thanks,
Max

**Comment by o-o00o-o** [comment]
i agree.. what is the difference?

**Comment by figueiredorui** [comment]
1-Click-Tasks only add Tasks to the parent WIT. 1-Click-Child-Links is able to add other types of WIT to the parent
