### ISSUE TITLE
Prefix tasks with a "tag"

### ISSUE THREAD

**Issue by gdelmee** [figueiredorui/1-click-child-links#11]
Creating a sytematic set of tasks is really nice. By the way, as tasks are assigned to users, when 'Development' tasks of several user stories are assigned to someone, he can't see directly to which user story each task belongs. He has to open detail and then jump to the parent.

A nice improvement would be to add a kind of "tag" to prefix the task's titles.

**Comment by eleshiarobinson** [comment]
I would love this capability to have a parameter or "tag" to automatically append the parent title in the child title.

**Comment by figueiredorui** [comment]
Wiki - [Copy fields value from parent](https://github.com/figueiredorui/1-click-child-links/wiki/Copy-fields-value-from-parent)
