### ISSUE TITLE
Having different groups of tasks for the same work item type

### ISSUE THREAD

**Issue by gdelmee** [figueiredorui/1-click-child-links#12]
A user story can follow complex steps with several tasks on it (I have one project going from 9 to 12 tasks for the standard process).
There are groups of tasks. A first set for requirements and their customer's validation. A second set for the design and their customer's validation. A third for development and tests. A fourth for UAT (core product and localizations).
For requirement and design phasis, without the validation, the user story is removed. Then, if we had created the overall tasks, tasks for phasis 3 and 4, and maybe phasis 2 are not relevant. It would be better if those were not created.

So being able to create different sets of tasks for the same type of WI can avoid creating a lot of tasks which may not yet be relevant in the backlog or which may potentially never be addressed.

**Comment by DomenicoFerrari** [comment]
I need it too.
Is it in roadmap?
Tnx

**Comment by omireault** [comment]
I have implemented this on my own fork. It uses a specific keyword in the title (e.g [Incubator] This is a Incubator story), and changes the Work Item filter to use curly braces {}. You just need to add the keyword to the description (e.g {User Stor} or [Incubator])

![image](https://user-images.githubusercontent.com/3998897/32013277-c7165468-b977-11e7-8fa8-f0afc9b378b7.png)

**Comment by Anthony9887** [comment]
Hi, 
Do you know when you plan to update the extension with these changes. 
This is exactly what I was looking for.
Thanks

**Comment by omireault** [comment]
I can do a pull request. I was concerned about the change from the [] to the {} to support my own needs.

**Comment by figueiredorui** [comment]
Hi @omireault, could you explain the reason for changing from [] to {} as a Work Item Type identifier.
I would be happy to accept a pull request but I'm concerned about backwards compatibility.
If we keep [] for Work Item Types we can use {} for fieldnames.

**Comment by omireault** [comment]
Honestly, it was just because of my company's use case. We are used to
tagging spikes and incubators with []. I can make the change and submit a
pull request.

**Comment by figueiredorui** [comment]
Wiki - [Group templates with identifier](https://github.com/figueiredorui/1-click-child-links/wiki/Group-templates-with-identifier)
