### ISSUE TITLE
The Tags (Add) field from the template is not being applied

### ISSUE THREAD

**Issue by pjzuber** [figueiredorui/1-click-child-links#13]
If I apply the template a task through the normal menu, the tag applies correctly, but when using 1-click child links it does not

**Comment by omireault** [comment]
Tasks are not currently supported. There is a comment in the code.

**Comment by figueiredorui** [comment]
Hi @omireault, any idea how to add Tags support?

**Comment by taimuralam** [comment]
I have forked this code and tweaked it a little to support tags. And it seems to for me now.

I can submit a PR if that would be helpful. @omireault @figueiredorui
