### ISSUE TITLE
Would like to insert PBI Title into title of task

### ISSUE THREAD

**Issue by robk410** [figueiredorui/1-click-child-links#15]
I'd like to specify a token within the task template title where this would insert the title of the associated PBI.

For example, my template title may be "Code Changes for {Title}" and then when this tool adds to the PBI titled "Implement Fix to Login Page" the final task title is "Code Changes for Implement Fix to Login Page"

**Comment by omireault** [comment]
I might be able to do something about this in my own branch. What's a PBI? And could you ellaborate?

**Comment by robk410** [comment]
Product Backlog Item - We use the Scrum template in VSTS and I would like to generate tasks under the PBI (Story) that would simply concat the PBI title onto the end of the template title. "Template Title" + "PBI Title"

**Comment by robk410** [comment]
maybe "{ParentTitle}" is a better token

**Comment by sduffy77** [comment]
I would also like to see this functionality

**Comment by figueiredorui** [comment]
Hi @robk410 , I know that @omireault has done some work regarding that functionality. I'm going to review it.

**Comment by omireault** [comment]
I haven't done anything with that specifically. I was working on it today, but didn't like my approach.

**Comment by figueiredorui** [comment]
Wiki - [Copy fields value from parent](https://github.com/figueiredorui/1-click-child-links/wiki/Copy-fields-value-from-parent)

**Comment by robk410** [comment]
Thank you!!
