### ISSUE TITLE
Inherit values from parent work item fields to child tasks

### ISSUE THREAD

**Issue by DevonBritton** [figueiredorui/1-click-child-links#17]
I have a specific customer who would like to inherit certain custom fields from the parent item down to the tasks created by 1 click child links. 

Is this possible?

**Comment by omireault** [comment]
It depends what fields you want inherited. Currently it already does a few fields. What did you have in mind?

**Comment by figueiredorui** [comment]
I have something in mind for this. 
If the template has a field with no value it would try to copy the value from the same field in parent WIT.

![image](https://user-images.githubusercontent.com/5295139/33784965-df1a0662-dc5a-11e7-8712-0fa46a4b70cc.png)

By the way @omireault , thanks for commenting/helping on the issues

**Comment by figueiredorui** [comment]
Wiki - [Inherit field values from parent work item](https://github.com/figueiredorui/1-click-child-links/wiki/Inherit-field-values-from-parent-work-item)

**Comment by DevonBritton** [comment]
Awesome!! Thanks!!

**Comment by omireault** [comment]
@figueiredorui You're welcome, I didn't do much. I am afraid I have left the world of VSTS and it's plugins. My new role uses JIRA, so I will not be able to help anymore.
