### ISSUE TITLE
Can't get it to work.

### ISSUE THREAD

**Issue by dwhittenburg** [figueiredorui/1-click-child-links#2]
Would love to use this, but I can't get it to work.

Added a template item to a bug
![image](https://cloud.githubusercontent.com/assets/7723714/21461830/56ef5c92-c923-11e6-9496-b74d042c756e.png)

When I pull up a bug and select the 1-click-child-links menu options, nothing happens.

**Comment by figueiredorui** [comment]
Hi,
I think you misunderstood the extension goal. The extension adds child links from predefined templates, means that when you looking at a bug it would add tasks as child links and when looking at a feature it would add bugs/PBIs.
![image](https://cloud.githubusercontent.com/assets/5295139/21462532/1b5ee9c2-c955-11e6-9f82-2fb743a82277.png)

**Comment by dwhittenburg** [comment]
So to add tasks to a bug, I need to add templates to tasks?

**Comment by figueiredorui** [comment]
correct.

**Comment by dwhittenburg** [comment]
Would that mean one set of task templates for both bugs and userStory/PBI?  We can't have a different template for PBI than Bugs?

**Comment by figueiredorui** [comment]
I'm working on that. 
Having some kind of identifier that can distinguish which tasks are added to Bugs, PBIs or both as a child link.

**Comment by dwhittenburg** [comment]
Perfect. I'll try it out the way you suggested. Thanks for creating this extension.

**Comment by dwhittenburg** [comment]
@figueiredorui I went back and added template to the tasks like below.  When I added the templates to a bug, it copied the title of the Bug for each task instead of copying the title of the task from the template.  This would provide a lot of value to me, so I want to provide feedback so you can look to see if you'd like.  Thank you.

![image](https://cloud.githubusercontent.com/assets/7723714/21499794/e810b668-cc06-11e6-9d0d-80e89a67d12a.png)

![image](https://cloud.githubusercontent.com/assets/7723714/21499814/25249934-cc07-11e6-9dd9-462f74885760.png)

**Comment by figueiredorui** [comment]
@dwhittenburg The Title of the Task is not defined by the Template Name, but, by the Title field on the Task template definition.

![image](https://cloud.githubusercontent.com/assets/5295139/21966065/58fc2b2a-db64-11e6-8fbb-863b9ed152db.png)

**Comment by gdobricic** [comment]
I noticed you were going to introduce identifier which can distinguish which tasks should be added to bugs, stories, etc. This would be a fantastic feature as we are moving from TeamPulse to VSTS and this is one of the features we miss the most. 
Is there an ETA for this feature, please?

**Comment by figueiredorui** [comment]
Hi @gdobricic , 
Thanks for your feedback. 
Adding a identifier to distinguish the tasks it's on the roadmap.
Regarding the sequence that the tasks appear on the work item I did some work in 
[1-Click Tasks](https://marketplace.visualstudio.com/items?itemName=ruifig.vsts-work-item-one-click-tasks)  extension to cope with this issue. I have notice that the tasks on the Work item they are ordered by User then by Title

It would be helpful to see if your tasks when added by [1-Click Tasks](https://marketplace.visualstudio.com/items?itemName=ruifig.vsts-work-item-one-click-tasks)  extension appear on correct order.

**Comment by gdobricic** [comment]
@figueiredorui Thanks for the update. We were actually using 1-click-child-links. Will this improvement be ported to that add-on, too?
Regards

**Comment by figueiredorui** [comment]
@gdobricic can you confirm that [1-Click Tasks](https://marketplace.visualstudio.com/items?itemName=ruifig.vsts-work-item-one-click-tasks) is adding the tasks on the correct order? if so, I'll implemenet same logic on 1-click-child-links

**Comment by gdobricic** [comment]
@figueiredorui, thank you. When adding items, items are not added in alphabetical order, but what is important is that the stack rank is correct. I can confirm that  1-Click Tasks is performing as desired. Thank you.

**Comment by figueiredorui** [comment]
Thanks for testing that. I will implement same logic on 1-click-child-links.

**Comment by gdobricic** [comment]
@figueiredorui Thanks. Maybe it is a good idea to close this "issue" before anything else is put in the same thread :)
