### ISSUE TITLE
Add 1-click links to custom work items as well

### ISSUE THREAD

**Issue by VinayKutty** [figueiredorui/1-click-child-links#24]
First of all, this extension has really saved us a lot of time in planning, so we're happy to be able to use it across our organization. Keep up the good work!

**Is there a way to add custom work items as child links too?**

The name "1-click-child-links" implies that we can add any types of child links to a work item. Unless I am mistaken, I am able to only add 1-click child _tasks_.

In our planning meetings, we have a Release Details (custom work item) task that is used by our release coordinator. This work item type is not a task per se, but it is still a child link in a PBI.

Example, below:

![image](https://user-images.githubusercontent.com/36705423/36491191-2d857142-16f8-11e8-9e48-a621db2e0059.png)

**Comment by jdshkolnik** [comment]
@VinayKutty Can we please see a screenshot of the "Backlog levels" page of this particular process template?

**Comment by VinayKutty** [comment]
@jdshkolnik Here you go!

![image](https://user-images.githubusercontent.com/36705423/54032348-56894700-417f-11e9-9c97-3a857cc78a8d.png)
