### ISSUE TITLE
Add a method to exclude template items.

### ISSUE THREAD

**Issue by AlexHimself** [figueiredorui/1-click-child-links#27]
I want to have a set of template items automatically added, but I also have some template items under a certain WIT that I don't want added, but I want available for users to use ad-hoc still.

**Comment by pabrams** [comment]
I have the same requirement. My client wants a dialog box to pop up after the "1-click" (of course, won't be 1-click anymore in that case) so they can choose which templates get created as child items.  I don't really like the dialog idea, but can't think of a better way to let them apply whatever combination of templates they want.

**Comment by tagir-gadelshin** [comment]
I'm also having troubles with all templates being used for creating new items. I want only one or two templates to be used, while having almost 10 templates in total

**Comment by jdshkolnik** [comment]
The pull request I submitted today for #29 should address all that.
