### ISSUE TITLE
Identifier to distinguish child links

### ISSUE THREAD

**Issue by figueiredorui** [figueiredorui/1-click-child-links#3]
Add Identifier to distinguish child links sets to be added as a subset in a single click instead of all

**Comment by figueiredorui** [comment]
@gdobricic

I have implemented a way of having an identifier to distinguish which child links tasks should be added to work items.
I've used the description to specify the identifiers.

![image](https://cloud.githubusercontent.com/assets/5295139/22847932/72e71944-efe8-11e6-89ad-ea1a19338e6f.png)

**Comment by gdobricic** [comment]
This is great! I tested it and it performs as you noted. One must only keep in mind that work items types in description are case sensitive, but that is ok!

**Comment by jdshkolnik** [comment]
It doesn't work with custom types in VSTS. I created a PBI clone called "Spike" and have some tasks without an identifier, some with Spike, yet none are created when I select 1-click-child-links.

**Comment by jdshkolnik** [comment]
When I tried it for a PBI just now, it also created a task not defined in any template: "Test for work item #378". I'm guessing that's debug code slipped into release.

**Comment by rui-tsgi-co** [comment]
I haven't tested it against custom types. I'll look into it. Thanks.

**Comment by figueiredorui** [comment]
@jdshkolnik , thanks for feedback. I'll add support for custom types.
