### ISSUE TITLE
Provide a way to sort tasks in custom order instead of alphabetically 

### ISSUE THREAD

**Issue by thesobercoder** [figueiredorui/1-click-child-links#33]
Currently there is no way to provide a custom task ordering logic. However this can be easily achieved by making the description a JSON and introducing an order field in it which can be used to sort the items.

FYI @jdshkolnik

**Comment by jdshkolnik** [comment]
We could definitely use the new JSON to define order although it'll be limited and a bit unintuitive in the cases where a single template applies to more than one filter. Example:

You have 4 templates, TaskA, TaskB, TaskC, TaskD.

For PBIs, you want them to appear like this:

1. TaskD
2. TaskB
3. TaskC

For a custom story-level item, you want:

1. TaskA
2. TaskB
3. TaskD

It's obviously impossible to assign a single order to each task template that would work. I think if someone wants the above case they'd have to make duplicates of the task templates for each variation.

The ordering logic should look for the order number and then secondary sort on title in ascending alphabetical. What do you think, @figueiredorui?

**Comment by assofohdz** [comment]
Any update on the ordering? :)

**Comment by figueiredorui** [comment]
Hi @assofohdz, a workaround is to prefix the Title with a number.

**Comment by assofohdz** [comment]
> Hi @assofohdz, a workaround is to prefix the Title with a number.

Thanks :) That'll work for us
