### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by omayhemo** [figueiredorui/1-click-child-links#34]
Using in Azure DevOps, has been working for months as configured.  Simple configuration, with two task templates.  I get the following when trying to use...

![image](https://user-images.githubusercontent.com/2934415/54548945-f82a4880-4976-11e9-8648-55799a51e4e9.png)

The task templates do in fact exist, and have existed in this configuration since I began using the extension.  It stopped working a week or two ago as far as I can tell.
![image](https://user-images.githubusercontent.com/2934415/54548980-0bd5af00-4977-11e9-919f-bdcc38c15331.png)

**Comment by MrLaffel** [comment]
We're experiencing the same behaviour, however not on all work item types. In our case we get "No templates found..." when using the extension on Bugs.

**Comment by mlennox22** [comment]
We are seeing the same issue after using it for several months without changing the configuration.  I'm assuming that something changed in Azure Boards?  Has anyone discovered any workarounds?  Sadly, we are in planning today and this is a valuable extension for that ceremony :(

![image](https://user-images.githubusercontent.com/29780066/54616753-8dd8dd00-4a36-11e9-9780-9aa4f019a468.png)

**Comment by figueiredorui** [comment]
I have just released a hotfix!

**Comment by bitsmithsys** [comment]
We have been using with TFS 2017 update 3 on-premises and this just started failing with this error after we restarted our TFS server.  It looks like following JS code is returning "undefined" for bugsBehavior:

bugsBehavior = workClient.getTeamSettings(team).bugsBehavior; //Off, AsTasks, AsRequirements

Is this the issue you have the hotfix for?  Also, I don't see anything on the TFS store newer that 3/13, which I did install, though it didn't resolve the issue.  Is this hotfix still in the process of being deployed there?

**Comment by figueiredorui** [comment]
Hi @bitsmithsys, I'm not familiar with TSF store. 
The latest version (v.0.10.1) is available here 
https://marketplace.visualstudio.com/items?itemName=ruifig.vsts-work-item-one-click-child-links

![image](https://user-images.githubusercontent.com/5295139/54625163-a6f98200-4a66-11e9-8ac5-07b546d42ffc.png)

**Comment by bitsmithsys** [comment]
@figueiredorui Yes, I see it there now.  I reinstalled and things are working again.  Thanks so much for creating this extension and the quick support in resolving the issue.

**Comment by mlennox22** [comment]
Just confirming that this works for us again.  Fantastic support in resolving this issue quickly!  Thank you!
