### ISSUE TITLE
1-click Child-Links is not working with specific AreaPath condition

### ISSUE THREAD

**Issue by srivivino** [figueiredorui/1-click-child-links#35]
Hi,

We are using below json code in description of task template to create a child tasks in PBI with area path condition, which is not working. kindly help us to make it work.
JSON_Code:
========
{
    "applywhen": [
    {
        "System.AreaPath" : "SHUI\WPF",
        "System.WorkItemType": "Product Backlog Item"
    }]
}

Regards,
Vinoth

**Comment by wilksmatt** [comment]
Hi, I'm having the same issue. Was there a resolution to make AreaPath work? Thanks.
