### ISSUE TITLE
Is it possible to attach Task templates to a Feature?

### ISSUE THREAD

**Issue by DevonBritton** [figueiredorui/1-click-child-links#40]
Hi @figueiredorui .

I've created some Task templates and I'm trying to add them to a Feature but it's not working. Is it only possible to add User Stories to Features and Tasks to User Stories?

Thanks. 
Devon.

**Comment by figueiredorui** [comment]
At the moment, the extension follows the processes defined
https://docs.microsoft.com/en-us/azure/devops/boards/work-items/guidance/choose-process?view=azure-devops&tabs=basic-process
