### ISSUE TITLE
Error .toLowerCase is not a function

### ISSUE THREAD

**Issue by biggunn** [figueiredorui/1-click-child-links#41]
Unable to get this extension to work.  Noticed in console I am getting this error:

TypeError: filterElement[fieldName].toLowerCase is not a function
at matchField (app.js:473)
at app.js:281

in my task templates I have the description as follows (as per the instructions):
{"applywhen":[{"System.Tags" : ["UX Core"]}]}

I am adding the tag "UX Core" in my **Product Backlog Item** and then trying to use the 1-click-child-links, but nothing happens.

Is this an error in the code, or am I doing something incorrect?

**Comment by figueiredorui** [comment]
Fixed on v0.11.1
