### ISSUE TITLE
Not able to create sets of task templates for 1-click

### ISSUE THREAD

**Issue by waardd** [figueiredorui/1-click-child-links#42]
I really want to use 1-click but i want to be able to make multiple sets of tasks to be linked to a PBI.
For example if we have a PBI called "Deploy to Production" i would like to have a set of subtasks to be linked with 1-click. But when i have a PBI called "New feature create webpage" i want another set to be linked to this PBI. How can i do this with 1-click.

I was used to task-templates in Jira to add multiple tasks to a story according to a template, i want that same functionality with 1-click in Azure DevOps.

**Comment by mwc360** [comment]
I'm looking for this same functionality...really need to have mutliple sets of tasks that can be created. Ideally when you click the button to add 1-click tasks if you have multiple defined sets you can choose which set to add.

**Comment by janmohammadi** [comment]
You can customize your process template and define different work item types.

[https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/customize-process-wit?view=azure-devops](url)
