### ISSUE TITLE
Only can create "task"

### ISSUE THREAD

**Issue by stu4355226** [figueiredorui/1-click-child-links#45]
In short word:

Even I place "[Test case]" in Description, the workItemTypeName is still set to "Task"

First, it fails at "IsValidTemplatedWIT", so it won't call "Createworkitem" function.
Second, if I make it pass, it will create a "Task" not a "Test Case" since the workItemTypeName = Task and it passes all the way through the "create work items".

I think it fails start from "GetChildTypes" function.

Please fix.

**Comment by figueiredorui** [comment]
Fixed on v0.11.1
