### ISSUE TITLE
One User cannot use 1 click child links

### ISSUE THREAD

**Issue by kimberlee14081** [figueiredorui/1-click-child-links#47]
We have one user that is using a laptop and is not able to use the one click child links - it shows up for her however when she clicks on it nothing happens. All the other members of the team have no issues. 
She is running Windows 10 Enterprise version 1903, 64-bit operating system, x64 based processor.
Has anyone else encountered this issue?

**Comment by sullise** [comment]
We have a  user that has same issue. Very frustrating.

**Comment by mpburtt** [comment]
It's very finicky about the user session's devOps team context. Check that the user who has the problem is in the right team and that they've been to a board and selected that team before they use the add-in.
