### ISSUE TITLE
System.Tags does not work for User Stories on System.WorkitemType: "Feature"

### ISSUE THREAD

**Issue by walkerjens** [figueiredorui/1-click-child-links#48]
System.Tags works fine for tasks, e.g.

{"applywhen":[{"System.WorkItemType": "User Story", "System.Tags": "Prestudy"}]}

However when I try to apply this to a User Story template, as such:

{"applywhen":[{"System.WorkItemType": "Feature", "System.Tags": "Prestudy"}]}

Nothing happens when I press 1-click-child-links. Removing the "System.Tags": "Prestudy", however yields the desired results where the User Story is created.

**Comment by figueiredorui** [comment]
Fixed on v0.11.1
