### ISSUE TITLE
System.Tags won't match if multiple tags on item

### ISSUE THREAD

**Issue by SnhuSpooner** [figueiredorui/1-click-child-links#50]
If I use the System.Tags in the applywhen clause, it will only match on items that only have that one tag on it.  If an item has that tag and other tags on it, then the applywhen clause fails.

For example, I have the following Description in a Task template:

{"applywhen":[{"System.Tags":"TagA"}]}

UserStory1 has only TagA
UserStory2 has TagA and TagB

The 1-click menu will add the Task for UserStory1 but not for UserStory2.  I expected it would match both given that TagA is on both items.

**Comment by SnhuSpooner** [comment]
This will work by adding an empty field:

{"applywhen":[{"System.Tags":"TagA"},{}]}

This now matches on UserStory1 and UserStory2 in the above example.

**Comment by figueiredorui** [comment]
Fixed on v0.11.1
