### ISSUE TITLE
1-click-childs not creating

### ISSUE THREAD

**Issue by ErikdeWit1** [figueiredorui/1-click-child-links#54]
We have 1-click-child-links configured to create tasks from User Stories, Bugs and Issues, but when we click on the '1-click-child-links' it does not create the Tasks. 

Below the logic we are using: 
{"applywhen": [{"System.WorkItemType": "User Story",}, {"System.WorkItemType": "Bug"}, {"System.WorkItemType": "Issue"}]}

**Comment by gaura711** [comment]
I get the alert "No Task templates found. Please add Task templates for the project team." 
Even though I have 2 task templates created under the project team.

**Comment by ErikdeWit1** [comment]
Also received that message today and we do have Task templates created under the project team/s. 

Would the way we structured our project and teams have an impact on this? We have 1 project with 3 sub-teams and some team members are assigned to one team only and others to all 3 teams. Should we create Task templates for each team separately, or will it cause conflict? 

What field on a Story determines the team that will be looked at by 1-click-childs, is it the Area Path?

**Comment by figueiredorui** [comment]
On Azure DevOps, the templates are defined per Team.

**Comment by ErikdeWit1** [comment]
@figueiredorui having templates defined per Team did not solve our issue.
