### ISSUE TITLE
Enhancement: Great tool but please add Bulk Create Child Tasks

### ISSUE THREAD

**Issue by hmelendez001** [figueiredorui/1-click-child-links#55]
Love the add-on, but is there a way to allow for Create Child Tasks for more than one work item at a time? For example, from a menu option in a Backlog list? That would be the one thing that would let us finally retire the PowerShell script we've been using to do this. Thank you!

**Comment by mpburtt** [comment]
You can already do this from a query. Once the query results are returned, highlight the work items that you want to trigger 1-Click for and then click the ellipsis (...) button on one of the highlighted work items and then select the 1-Click Child-Links option on the context menu that pops up.

**Comment by SvendK** [comment]
Uh, nice! I guess this is also possible from the (Scrum) Boards, Sprints, (sprint) Backlog - then you can do this for the entire commencing sprint. Nice!

**Comment by figueiredorui** [comment]
Great! Thanks @mpburtt
