### ISSUE TITLE
Children not always added from board or backlog view

### ISSUE THREAD

**Issue by mkeresz1** [figueiredorui/1-click-child-links#58]
We are experiencing intermittent issues when attempting to use the extension in the backlog or board view. It doesn't seem to add the children the same way it does if a PBI is open.

**Comment by SvendK** [comment]
We also experience this. I believe (without having looked at the code) that the issue is that each task creation invokes a timer that, when timeout, refreshes the page. If the client javascript haven't created all tasks, the operation is not finished.

**Comment by figueiredorui** [comment]
Added a small delay before refreshing. Hope it helps
