### ISSUE TITLE
Is this github abandoned?

### ISSUE THREAD

**Issue by SvendK** [figueiredorui/1-click-child-links#59]
Hi figueiredorui

Thank you for this project, it's really great. I'm worrying though that there is 2 pull requests still open since 2018 and issues is not answered. I know that this is a free software and thanks again, but if issues is not solved, we might have to find something else. Can we fork this? Or am I actually mistaken in the active-ness of the project?

Thanks again! :-)

Best regards
SvendK

**Comment by figueiredorui** [comment]
I have fixed a few bugs and added a couple of enhancements.
Released and published a new version.
