### ISSUE TITLE
Add support for template set selection

### ISSUE THREAD

**Issue by fjdiazt** [figueiredorui/1-click-child-links#6]
Support for template selection could be implemented in a similar way to custom types, by using the decription field as a "set identifier" (or group identifier). When selecting the "1-click-Child-links" menu, a pop up would ask the user which "set" to use, and identify the set by the template description.

Is it possible to request user input when clicking a link in this extensions?

**Comment by Tom-Spring** [comment]
That's a very good idea! I Would appreciate that functionality as well!

**Comment by RealAdamSinger** [comment]
This is exactly what we are looking for. 
The current functionality is nice but we are limited to a single template for each item type right now. Would be really helpful to create multiple sets!

**Comment by figueiredorui** [comment]
Thanks for feedback and suggestions. This will be considered in future development.

**Comment by russelldyas** [comment]
Great work and to add my support to this feature ideas.  The lack of "sets" is blocking us using it in a major way etc.

**Comment by HitM47** [comment]
Have you some news about set selection ?
