### ISSUE TITLE
After latest update to ver. 0.11.2 using minified (single line) JSON string stopped working properly

### ISSUE THREAD

**Issue by p-adi** [figueiredorui/1-click-child-links#62]
Hi,
I'm using cloud version of Azure DevOps and copy of Agile process. 1-Click is very helpfull for my team from over one year ... but after latest update it creates lots of unesessary taskas.

I've 2 groups of 3 tasks which are distinguished by diferent tags - the JSON string put in description filed looks like this:

Group 1:
{"applywhen": [ { "System.WorkItemType": "User Story", "System.State" : "New" ,"System.Tags": "Group1" }] }

Group 2:
{"applywhen": [ { "System.WorkItemType": "User Story", "System.State" : "New" ,"System.Tags": "Group2" }] }

With such configuration if User Story had tag "Group1" and state set to new 1-Click generates set of 3 tasks, and if User Story had tag "Group2" and state set to new 1-Click generates set of 3 other tasks.
After yesterday update 1-Click generates 6 tasks instead 3 (it does not matter which tag is set Group1 or Group2) - like it does not see the tag. Also when the state of user story is defferent then "New" (for instance "Closed") all 6 tasks are also created.

**Comment by figueiredorui** [comment]
Hi @p-adi, thanks for reporting the issue. I believe is fixed now!

**Comment by Alexandre540** [comment]
Hi @figueiredorui  With the last update it doesn't work for me, even if i try the easiest setup like 

{"applywhen": [ { "System.State": "Active" } ] }

Thanks for your help.
