### ISSUE TITLE
Error message but no issue

### ISSUE THREAD

**Issue by rotulf** [figueiredorui/1-click-child-links#63]
I got an error message when I create child tasks.
* parent is "Issue" work item 
* child is "Task"
* one-click should create 29 children
* during creation of the child items the following error appears:
"Error saving: [object Object]"
* al child items are created 

![image](https://user-images.githubusercontent.com/44051482/84155359-8ac97280-aa68-11ea-998e-599095cdf031.png)

**Comment by figueiredorui** [comment]
Hi @rotulf, I have fixed a few things. Are you still have this issue?

**Comment by rotulf** [comment]
Hi 
I no longer see this issue. 
Thanks!
