### ISSUE TITLE
1-click no longer generating tasks

### ISSUE THREAD

**Issue by ahardin13** [figueiredorui/1-click-child-links#64]
Today 1-click stopped generating tasks for us.  It did work yesterday (before we received v 0.11.3).

Here is an example of a previously working task:
![image](https://user-images.githubusercontent.com/12464376/84156794-f3e4c200-aa37-11ea-86be-328f6978f534.png)

Version screenshot:
![image](https://user-images.githubusercontent.com/12464376/84156533-9c465680-aa37-11ea-88a6-8fc6c817324b.png)

**Comment by figueiredorui** [comment]
Hi @ahardin13 , somehow I managed to publish a development version of the extension.
Would you give it another go!

**Comment by ahardin13** [comment]
@figueiredorui That fixed it!  Thanks!
