### ISSUE TITLE
After update 0.11.3 tasks are not creating at all

### ISSUE THREAD

**Issue by p-adi** [figueiredorui/1-click-child-links#65]
After update 0.11.3 tasks are not creating at all - no mather what  is in description field eg:

{"applywhen":[{"System.WorkItemType":"User Story", "System.State":"New", "System.Tags":"group1"}]}
or
{"applywhen":[{"System.WorkItemType":"User Story", "System.State":"New"}]}
or
{"applywhen":[{"System.WorkItemType":"User Story"}]}
or
[User Story]
or 
description field is empty.

**Comment by figueiredorui** [comment]
Hi @p-adi, somehow I managed to publish a development version.
Would you give it another go!

**Comment by Alexandre540** [comment]
@figueiredorui  Still the same, even with the easiest setup  
{"applywhen":[{"System.WorkItemType":"User Story"}]}

**Comment by p-adi** [comment]
Hi @figueiredorui , @Alexandre540 
after update to 0.11.5 creating tasks for User Story works ok - I've tested all below configurations:

- {"applywhen":[{"System.WorkItemType":"User Story", "System.State":"New", "System.Tags":"group1"}]}
- {"applywhen":[{"System.WorkItemType":"User Story", "System.State":"New"}]}
- {"applywhen":[{"System.WorkItemType":"User Story"}]}
- [User Story]

but for Bug creating tasks works only for such configurations:
- [Bug]
- description field is empty

When I use:
- {"applywhen":[{"System.WorkItemType":"Bug", "System.State":"New", "System.Tags":"group1"}]}
- {"applywhen":[{"System.WorkItemType":"Bug", "System.State":"New"}]}
- {"applywhen":[{"System.WorkItemType":"Bug"}]}

tasks are not creating.

@Alexandre540 do you use DevOps on-premise or on cloud ?

**Comment by Alexandre540** [comment]
Hi @p-adi . Thanks for your reply.

I use DevOps on cloud and one click is in the last version 0.11.5.

I try to delete and start again all my setup.

**Comment by DiegoLenis** [comment]
We are still having issues even with version 11.6

**Comment by figueiredorui** [comment]
I have added some trace to the DevTools console that will help to understand what is wrong.

**Comment by mpburtt** [comment]
@figueiredorui The addition of the info in the DevTools console has been invaluable, thanks! Using the console, I discovered that one of my templates had some invalid JSON and that was throwing an error which I could see in the console and the info messages you are now writing told me which template had the problem. We don't see any error message in the DevOps UI when the extension hits an error like this though, so it just looks to the end user like the template wasn't found. It would be useful to get something surfaced in the UI so that its immediately apparent that there's a problem with the template, especially when it's really quite easy to make a mistake in constructing the JSON.

**Comment by figueiredorui** [comment]
Thanks @mpburtt, I'll make some improvements to the error messages.

**Comment by DiegoLenis** [comment]
@figueiredorui Still not working properly with 0.11.11. In some teams no child task are created, while in others a few task are created. See below json for non working template that worked on version .0.11.3

{"applywhen":[{"System.State":"Committed to Refine","System.WorkItemType":"Defect"},{"System.State":"Committed to Refine","System.WorkItemType":"Product Backlog Item"},{"System.State":"Committed to Implement","System.WorkItemType":"Refine Feature"},{"System.State":"Committed to Refine","System.WorkItemType":"Technical Feasibility Spike"}]}

Thank you,

**Comment by figueiredorui** [comment]
There was a breaking change on the latest version
The filter template no longer allows multiple filters
You have to create multiple templates.

```
{
    "applywhen": {
            "System.State": "Committed to Refine",
            "System.WorkItemType": "Defect"
        }
    
}
```

or

```
{
    "applywhen": [{
            "System.State": "Committed to Refine",
            "System.WorkItemType": "Defect"
        }
    ]
}
```

**Comment by thesobercoder** [comment]
@figueiredorui Any reason for this breaking change? The multiple criteria was working completely fine.

**Comment by figueiredorui** [comment]
This was due to the fact that now allows filtering by any field. I'm looking into bringing the multiple multiple filters back

**Comment by DiegoLenis** [comment]
@figueiredorui Do you have a timeline when and if multiple filters are added back?

**Comment by figueiredorui** [comment]
Hi @DiegoLenis, I have added back the multi filters option.
Have a go!

**Comment by DiegoLenis** [comment]
@figueiredorui Seems to be working correctly. Thank you!
