### ISSUE TITLE
Don't know where to start

### ISSUE THREAD

**Issue by RayWileman** [figueiredorui/1-click-child-links#8]
I installed this and really want to use it in TFS 2015..

but can't find where 

![clild click](https://user-images.githubusercontent.com/29574255/27333917-265444d4-558d-11e7-8abb-3178773919b4.JPG)

is located on the web portal.

**Comment by figueiredorui** [comment]
Hi @RayWileman 

Create / Open a Work Item

Find 1-Click Child-Links on toolbar menu

![image](https://user-images.githubusercontent.com/5295139/27335737-771245dc-55c5-11e7-9a85-1020fae76548.png)

**Comment by RayWileman** [comment]
I see
![image](https://user-images.githubusercontent.com/29574255/27337171-454d8634-5597-11e7-8346-33b96f1c86c3.png)

but there is not a drop down

**Comment by RayWileman** [comment]
thanks for the quick response!
