### ISSUE TITLE
Where to Find System Name References for JSON Descriptions

### ISSUE THREAD

**Issue by ultrawide** [figueiredorui/1-click-child-links#85]
Hello, where can I find documentation on the key-value pair variables? For example, if I want to add a condition for Priority, I can enter in `System.Priority`. I am able to do this by inferring the name, but it would be better if there is a list I can reference off of.

I wasn't able to find documentation or a related issue on this. Any help is appreciated!

```
{
    "applywhen": 
    {
        "System.State": "Approved",
        "System.Tags" : ["CustomerBug", "Product1"],
        "System.WorkItemType": "Product Backlog Item"
    }
}
```

**Comment by sanketraj8** [comment]
Use witadmin command to get the complete list. [Link](https://docs.microsoft.com/en-us/azure/devops/reference/witadmin/witadmin-customize-and-manage-objects-for-tracking-work?view=azure-devops-2020)

 Enter the following commands in command prompt and replace 2017 with your VS version and tfs_url with you base tfs url.

- cd %programfiles(x86)%\Microsoft Visual Studio\2017\Professional\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer
- witadmin listfields /collection:tfs_url

The output will give you all the parameters. You can save them in a notepad file for future reference.
