### ISSUE TITLE
Don't see a drop down to create templates

### ISSUE THREAD

**Issue by RayWileman** [figueiredorui/1-click-child-links#9]
Seems like this is exactly that I need..

Using TFS 2015

I don't see a drop down.. 
am I in the right place?
![image](https://user-images.githubusercontent.com/29574255/27345967-230556dc-55b1-11e7-9114-9bde13cb0776.png)

**Comment by figueiredorui** [comment]
That is the right option.

**Comment by RayWileman** [comment]
I am using chrome.. I also tried in fire fox... I am using TFS 2015 


Here is the installed extention...
![image](https://user-images.githubusercontent.com/29574255/27347529-80c0d45e-55b6-11e7-8790-5945c3a3fc77.png)

is there some other set up need?  thanks again for the quick response.

**Comment by figueiredorui** [comment]
Honestly, I'm not familiar with TFS 2015. The extension was developed and tested in VSTS.

**Comment by RayWileman** [comment]
AAhhh... that will explain it.. please close the ticket... thanks again!
